#!/bin/bash

##runs a number of BiCarving jobs couple to issuing console to generate meshgen pillar configurations
##Markus Kuehbach, 2018/10/01, m.kuehbach at mpie.de
exenm="bicarving_systematic_xrot"

simid="1005"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +5.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1010"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +10.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1015"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +15.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1020"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +20.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1025"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +25.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1030"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +30.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1035"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +35.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1040"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +40.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1045"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +45.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1050"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +50.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1055"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +55.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1060"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +60.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1065"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +65.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1070"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +70.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1075"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +75.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1080"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +80.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
simid="1085"
eval "mpirun -np 1 ./${exenm} ${simid} BiCarving.xml +1.0 +0.0 +0.0 +85.0 1>BiCarving.SimID.${simid}.STDOUT.txt 2>BiCarving.SimID.${simid}.STDERR.txt"
